// <auto-generated />
using System;
using IconIK.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IconIK.API.Migrations
{
    [DbContext(typeof(IconIKContext))]
    [Migration("20250906152415_PersonelOzlukBilgileriEkleme")]
    partial class PersonelOzlukBilgileriEkleme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BilgeLojistikIK.API.Models.AvansTalebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("aciklama");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OnayDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("onay_durumu");

                    b.Property<string>("OnayNotu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("onay_notu");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onay_tarihi");

                    b.Property<int?>("OnaylayanId")
                        .HasColumnType("integer")
                        .HasColumnName("onaylayan_id");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer")
                        .HasColumnName("personel_id");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("talep_tarihi");

                    b.Property<decimal>("TalepTutari")
                        .HasColumnType("numeric")
                        .HasColumnName("talep_tutari");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OnaylayanId");

                    b.HasIndex("PersonelId");

                    b.ToTable("avans_talepleri");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ad");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kod");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("departmanlar");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Egitim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("baslangic_tarihi");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("baslik");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bitis_tarihi");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("durum");

                    b.Property<string>("Egitmen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("egitmen");

                    b.Property<int?>("Kapasite")
                        .HasColumnType("integer")
                        .HasColumnName("kapasite");

                    b.Property<string>("Konum")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("konum");

                    b.Property<int?>("SureSaat")
                        .HasColumnType("integer")
                        .HasColumnName("sure_saat");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("egitimler");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.EkranYetkisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EkranAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EkranKodu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EkranKodu")
                        .IsUnique();

                    b.ToTable("EkranYetkileri");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.IstifaTalebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IstifaNedeni")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("istifa_nedeni");

                    b.Property<DateTime>("IstifaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("istifa_tarihi");

                    b.Property<string>("OnayDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("onay_durumu");

                    b.Property<string>("OnayNotu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("onay_notu");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onay_tarihi");

                    b.Property<int?>("OnaylayanId")
                        .HasColumnType("integer")
                        .HasColumnName("onaylayan_id");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer")
                        .HasColumnName("personel_id");

                    b.Property<DateTime>("SonCalismaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("son_calisma_tarihi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OnaylayanId");

                    b.HasIndex("PersonelId");

                    b.ToTable("istifa_talepleri");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.IzinTalebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("durum");

                    b.Property<string>("GorevYeri")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gorev_yeri");

                    b.Property<int>("GunSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("gun_sayisi");

                    b.Property<DateTime>("IsbasiTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("isbasi_tarihi");

                    b.Property<DateTime>("IzinBaslamaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("izin_baslama_tarihi");

                    b.Property<string>("IzinTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("izin_tipi");

                    b.Property<string>("OnayNotu")
                        .HasColumnType("text")
                        .HasColumnName("onay_notu");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onay_tarihi");

                    b.Property<int?>("OnaylayanId")
                        .HasColumnType("integer")
                        .HasColumnName("onaylayan_id");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer")
                        .HasColumnName("personel_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OnaylayanId");

                    b.HasIndex("PersonelId");

                    b.ToTable("izin_talepleri", t =>
                        {
                            t.HasCheckConstraint("CK_IzinTalebi_Durum", "durum IN ('Beklemede', 'Onaylandý', 'Reddedildi')");
                        });
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Kademe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ad");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Seviye")
                        .HasColumnType("integer")
                        .HasColumnName("seviye");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.HasIndex("Seviye")
                        .IsUnique();

                    b.ToTable("kademeler");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.KademeEkranYetkisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EkranYetkisiId")
                        .HasColumnType("integer");

                    b.Property<bool>("GuncellemeYetkisi")
                        .HasColumnType("boolean");

                    b.Property<int>("KademeId")
                        .HasColumnType("integer");

                    b.Property<bool>("OkumaYetkisi")
                        .HasColumnType("boolean");

                    b.Property<bool>("SilmeYetkisi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("YazmaYetkisi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EkranYetkisiId");

                    b.HasIndex("KademeId", "EkranYetkisiId")
                        .IsUnique();

                    b.ToTable("KademeEkranYetkileri");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IlkGiris")
                        .HasColumnType("boolean")
                        .HasColumnName("ilk_giris");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kullanici_adi");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer")
                        .HasColumnName("personel_id");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sifre_hash");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("son_giris_tarihi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.HasIndex("PersonelId")
                        .IsUnique();

                    b.ToTable("kullanicilar");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcilDurumIletisim")
                        .HasColumnType("text")
                        .HasColumnName("acil_durum_iletisim");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ad");

                    b.Property<string>("Adres")
                        .HasColumnType("text")
                        .HasColumnName("adres");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<string>("AnneAdi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("anne_adi");

                    b.Property<string>("AskerlikDurumu")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("askerlik_durumu");

                    b.Property<string>("BabaAdi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("baba_adi");

                    b.Property<string>("BankaHesapNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("banka_hesap_no");

                    b.Property<DateTime?>("CikisTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cikis_tarihi");

                    b.Property<string>("Cinsiyet")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cinsiyet");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dogum_tarihi");

                    b.Property<string>("DogumYeri")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dogum_yeri");

                    b.Property<string>("EgitimDurumu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("egitim_durumu");

                    b.Property<string>("EhliyetSinifi")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ehliyet_sinifi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FotografUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fotograf_url");

                    b.Property<string>("IbanNo")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("iban_no");

                    b.Property<DateTime>("IseBaslamaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ise_baslama_tarihi");

                    b.Property<string>("KanGrubu")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("kan_grubu");

                    b.Property<decimal?>("Maas")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("maas");

                    b.Property<string>("MedeniHal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("medeni_hal");

                    b.Property<string>("NufusIlKod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nufus_il_kod");

                    b.Property<string>("NufusIlceKod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nufus_ilce_kod");

                    b.Property<int>("PozisyonId")
                        .HasColumnType("integer")
                        .HasColumnName("pozisyon_id");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("soyad");

                    b.Property<string>("TcKimlik")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("tc_kimlik");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefon");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("YoneticiId")
                        .HasColumnType("integer")
                        .HasColumnName("yonetici_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PozisyonId");

                    b.HasIndex("TcKimlik")
                        .IsUnique();

                    b.HasIndex("YoneticiId");

                    b.ToTable("personeller");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.PersonelEgitimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EgitimId")
                        .HasColumnType("integer")
                        .HasColumnName("egitim_id");

                    b.Property<string>("KatilimDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("katilim_durumu");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer")
                        .HasColumnName("personel_id");

                    b.Property<int?>("Puan")
                        .HasColumnType("integer")
                        .HasColumnName("puan");

                    b.Property<string>("SertifikaUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sertifika_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EgitimId");

                    b.HasIndex("PersonelId");

                    b.ToTable("personel_egitimleri");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.PersonelZimmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("durum");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi");

                    b.Property<int?>("IadeAlanId")
                        .HasColumnType("integer")
                        .HasColumnName("iade_alan_id");

                    b.Property<string>("IadeNotu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("iade_notu");

                    b.Property<DateTime?>("IadeTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iade_tarihi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer")
                        .HasColumnName("personel_id");

                    b.Property<int>("ZimmetMiktar")
                        .HasColumnType("integer")
                        .HasColumnName("zimmet_miktar");

                    b.Property<string>("ZimmetNotu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("zimmet_notu");

                    b.Property<int>("ZimmetStokId")
                        .HasColumnType("integer")
                        .HasColumnName("zimmet_stok_id");

                    b.Property<DateTime>("ZimmetTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("zimmet_tarihi");

                    b.Property<int?>("ZimmetVerenId")
                        .HasColumnType("integer")
                        .HasColumnName("zimmet_veren_id");

                    b.HasKey("Id");

                    b.HasIndex("IadeAlanId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("ZimmetStokId");

                    b.HasIndex("ZimmetVerenId");

                    b.ToTable("personel_zimmet", t =>
                        {
                            t.HasCheckConstraint("CK_PersonelZimmet_Durum", "durum IN ('Zimmetli', 'Iade Edildi')");
                        });
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Pozisyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ad");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("integer")
                        .HasColumnName("departman_id");

                    b.Property<int>("KademeId")
                        .HasColumnType("integer")
                        .HasColumnName("kademe_id");

                    b.Property<decimal?>("MaxMaas")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("max_maas");

                    b.Property<decimal?>("MinMaas")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("min_maas");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("KademeId");

                    b.HasIndex("Ad", "DepartmanId", "KademeId")
                        .IsUnique();

                    b.ToTable("pozisyonlar");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoAtama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtamaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AtayanPersonelId")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartmanId")
                        .HasColumnType("integer");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("HatirlatmaGonderildiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Not")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<int?>("PozisyonId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SonHatirlatmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VideoEgitimId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtayanPersonelId");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("PozisyonId");

                    b.HasIndex("VideoEgitimId");

                    b.ToTable("VideoAtamalar");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoEgitim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Egitmen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IzlenmeMinimum")
                        .HasColumnType("integer");

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Seviye")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SonTamamlanmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sure")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("ZorunluMu")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("VideoEgitimler");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoIzleme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CihazTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAdresi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("IzlemeBaslangic")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IzlemeBitis")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IzlemeYuzdesi")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<int?>("Puan")
                        .HasColumnType("integer");

                    b.Property<bool>("TamamlandiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ToplamIzlenenSure")
                        .HasColumnType("integer");

                    b.Property<int>("VideoEgitimId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("VideoEgitimId");

                    b.ToTable("VideoIzlemeler");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("VideoKategoriler");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoSertifika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GecerlilikTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IzlemeYuzdesi")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<int?>("QuizPuani")
                        .HasColumnType("integer");

                    b.Property<string>("SertifikaNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SertifikaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("VerilmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VideoEgitimId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("VideoEgitimId");

                    b.ToTable("VideoSertifikalar");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoSoru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("CevapA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CevapB")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CevapC")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CevapD")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DogruCevap")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("Puan")
                        .HasColumnType("integer");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.Property<string>("Soru")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("VideoEgitimId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VideoEgitimId");

                    b.ToTable("VideoSorular");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoSoruCevap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlinanPuan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CevapTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DogruMu")
                        .HasColumnType("boolean");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<string>("VerilenCevap")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("VideoSoruId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("VideoSoruId");

                    b.ToTable("VideoSoruCevaplar");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoYorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<int?>("Puan")
                        .HasColumnType("integer");

                    b.Property<int>("VideoEgitimId")
                        .HasColumnType("integer");

                    b.Property<string>("Yorum")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("YorumTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("VideoEgitimId");

                    b.ToTable("VideoYorumlar");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Zimmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<bool>("BilgisayarCantasi")
                        .HasColumnType("boolean")
                        .HasColumnName("bilgisayar_cantasi");

                    b.Property<string>("BilgisayarCantasiDetay")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bilgisayar_cantasi_detay");

                    b.Property<bool>("CepTelefonu")
                        .HasColumnType("boolean")
                        .HasColumnName("cep_telefonu");

                    b.Property<string>("CepTelefonuDetay")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cep_telefonu_detay");

                    b.Property<bool>("DizustuBilgisayar")
                        .HasColumnType("boolean")
                        .HasColumnName("dizustu_bilgisayar");

                    b.Property<string>("DizustuBilgisayarDetay")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dizustu_bilgisayar_detay");

                    b.Property<string>("DokumanNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dokuman_no");

                    b.Property<string>("ErisimYetkileri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("erisim_yetkileri");

                    b.Property<bool>("GsmHat")
                        .HasColumnType("boolean")
                        .HasColumnName("gsm_hat");

                    b.Property<string>("GsmHatDetay")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gsm_hat_detay");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi");

                    b.Property<string>("Hazirlayan")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hazirlayan");

                    b.Property<bool>("Klavye")
                        .HasColumnType("boolean")
                        .HasColumnName("klavye");

                    b.Property<bool>("Monitor")
                        .HasColumnType("boolean")
                        .HasColumnName("monitor");

                    b.Property<string>("MonitorDetay")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("monitor_detay");

                    b.Property<bool>("Mouse")
                        .HasColumnType("boolean")
                        .HasColumnName("mouse");

                    b.Property<bool>("OfisTelefonu")
                        .HasColumnType("boolean")
                        .HasColumnName("ofis_telefonu");

                    b.Property<string>("OfisTelefonuDetay")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ofis_telefonu_detay");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi");

                    b.Property<string>("Onaylayan")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("onaylayan");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer")
                        .HasColumnName("personel_id");

                    b.Property<string>("TeslimAlmaNotlari")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("teslim_alma_notlari");

                    b.Property<bool>("TeslimDurumu")
                        .HasColumnType("boolean")
                        .HasColumnName("teslim_durumu");

                    b.Property<string>("TeslimEden")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("teslim_eden");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("teslim_tarihi");

                    b.Property<bool>("YemekKarti")
                        .HasColumnType("boolean")
                        .HasColumnName("yemek_karti");

                    b.Property<string>("YemekKartiDetay")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("yemek_karti_detay");

                    b.Property<DateTime>("ZimmetTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("zimmet_tarihi");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("zimmetler");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.ZimmetMalzeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Miktar")
                        .HasColumnType("integer")
                        .HasColumnName("miktar");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi");

                    b.Property<int>("ZimmetId")
                        .HasColumnType("integer")
                        .HasColumnName("zimmet_id");

                    b.Property<int>("ZimmetStokId")
                        .HasColumnType("integer")
                        .HasColumnName("zimmet_stok_id");

                    b.HasKey("Id");

                    b.HasIndex("ZimmetId");

                    b.HasIndex("ZimmetStokId");

                    b.ToTable("zimmet_malzemeler");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.ZimmetStok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("aciklama");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<string>("Birim")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("birim");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guncelleme_tarihi");

                    b.Property<int>("KalanMiktar")
                        .HasColumnType("integer")
                        .HasColumnName("kalan_miktar");

                    b.Property<string>("Kategori")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("kategori");

                    b.Property<string>("MalzemeAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("malzeme_adi");

                    b.Property<string>("Marka")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marka");

                    b.Property<int>("Miktar")
                        .HasColumnType("integer")
                        .HasColumnName("miktar");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<int?>("OlusturanId")
                        .HasColumnType("integer")
                        .HasColumnName("olusturan_id");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi");

                    b.Property<string>("OnayDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("onay_durumu");

                    b.Property<string>("OnayNotu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("onay_notu");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onay_tarihi");

                    b.Property<int?>("OnaylayanId")
                        .HasColumnType("integer")
                        .HasColumnName("onaylayan_id");

                    b.Property<string>("SeriNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("seri_no");

                    b.HasKey("Id");

                    b.HasIndex("OlusturanId");

                    b.HasIndex("OnaylayanId");

                    b.ToTable("zimmet_stok", t =>
                        {
                            t.HasCheckConstraint("CK_ZimmetStok_OnayDurumu", "onay_durumu IN ('Bekliyor', 'Onaylandi', 'Reddedildi')");
                        });
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.ZimmetStokDosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dosya_adi");

                    b.Property<long>("DosyaBoyutu")
                        .HasColumnType("bigint")
                        .HasColumnName("dosya_boyutu");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dosya_yolu");

                    b.Property<string>("MimeTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_tipi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturma_tarihi");

                    b.Property<string>("OrijinalAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("orijinal_adi");

                    b.Property<int>("ZimmetStokId")
                        .HasColumnType("integer")
                        .HasColumnName("zimmet_stok_id");

                    b.HasKey("Id");

                    b.HasIndex("ZimmetStokId");

                    b.ToTable("zimmet_stok_dosyalar");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.AvansTalebi", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Onaylayan")
                        .WithMany()
                        .HasForeignKey("OnaylayanId");

                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Onaylayan");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.IstifaTalebi", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Onaylayan")
                        .WithMany()
                        .HasForeignKey("OnaylayanId");

                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Onaylayan");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.IzinTalebi", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Onaylayan")
                        .WithMany("OnayladigiIzinler")
                        .HasForeignKey("OnaylayanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Personel")
                        .WithMany("IzinTalepleri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Onaylayan");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.KademeEkranYetkisi", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.EkranYetkisi", "EkranYetkisi")
                        .WithMany("KademeYetkileri")
                        .HasForeignKey("EkranYetkisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilgeLojistikIK.API.Models.Kademe", "Kademe")
                        .WithMany()
                        .HasForeignKey("KademeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EkranYetkisi");

                    b.Navigation("Kademe");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Kullanici", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Personel")
                        .WithOne("Kullanici")
                        .HasForeignKey("BilgeLojistikIK.API.Models.Kullanici", "PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Personel", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Pozisyon", "Pozisyon")
                        .WithMany("Personeller")
                        .HasForeignKey("PozisyonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Yonetici")
                        .WithMany("AltCalisanlar")
                        .HasForeignKey("YoneticiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pozisyon");

                    b.Navigation("Yonetici");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.PersonelEgitimi", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Egitim", "Egitim")
                        .WithMany("PersonelEgitimleri")
                        .HasForeignKey("EgitimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Personel")
                        .WithMany("PersonelEgitimleri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Egitim");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.PersonelZimmet", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "IadeAlan")
                        .WithMany()
                        .HasForeignKey("IadeAlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BilgeLojistikIK.API.Models.ZimmetStok", "ZimmetStok")
                        .WithMany()
                        .HasForeignKey("ZimmetStokId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "ZimmetVeren")
                        .WithMany()
                        .HasForeignKey("ZimmetVerenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IadeAlan");

                    b.Navigation("Personel");

                    b.Navigation("ZimmetStok");

                    b.Navigation("ZimmetVeren");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Pozisyon", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Departman", "Departman")
                        .WithMany("Pozisyonlar")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BilgeLojistikIK.API.Models.Kademe", "Kademe")
                        .WithMany("Pozisyonlar")
                        .HasForeignKey("KademeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departman");

                    b.Navigation("Kademe");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoAtama", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "AtayanPersonel")
                        .WithMany()
                        .HasForeignKey("AtayanPersonelId");

                    b.HasOne("BilgeLojistikIK.API.Models.Departman", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanId");

                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId");

                    b.HasOne("BilgeLojistikIK.API.Models.Pozisyon", "Pozisyon")
                        .WithMany()
                        .HasForeignKey("PozisyonId");

                    b.HasOne("BilgeLojistikIK.API.Models.VideoEgitim", "VideoEgitim")
                        .WithMany("VideoAtamalar")
                        .HasForeignKey("VideoEgitimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtayanPersonel");

                    b.Navigation("Departman");

                    b.Navigation("Personel");

                    b.Navigation("Pozisyon");

                    b.Navigation("VideoEgitim");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoEgitim", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.VideoKategori", "Kategori")
                        .WithMany("VideoEgitimler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoIzleme", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilgeLojistikIK.API.Models.VideoEgitim", "VideoEgitim")
                        .WithMany("VideoIzlemeler")
                        .HasForeignKey("VideoEgitimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("VideoEgitim");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoSertifika", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilgeLojistikIK.API.Models.VideoEgitim", "VideoEgitim")
                        .WithMany()
                        .HasForeignKey("VideoEgitimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("VideoEgitim");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoSoru", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.VideoEgitim", "VideoEgitim")
                        .WithMany("VideoSorular")
                        .HasForeignKey("VideoEgitimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoEgitim");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoSoruCevap", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilgeLojistikIK.API.Models.VideoSoru", "VideoSoru")
                        .WithMany("VideoSoruCevaplar")
                        .HasForeignKey("VideoSoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("VideoSoru");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoYorum", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilgeLojistikIK.API.Models.VideoEgitim", "VideoEgitim")
                        .WithMany("VideoYorumlar")
                        .HasForeignKey("VideoEgitimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("VideoEgitim");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Zimmet", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.ZimmetMalzeme", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Zimmet", "Zimmet")
                        .WithMany()
                        .HasForeignKey("ZimmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilgeLojistikIK.API.Models.ZimmetStok", "ZimmetStok")
                        .WithMany()
                        .HasForeignKey("ZimmetStokId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zimmet");

                    b.Navigation("ZimmetStok");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.ZimmetStok", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Olusturan")
                        .WithMany()
                        .HasForeignKey("OlusturanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BilgeLojistikIK.API.Models.Personel", "Onaylayan")
                        .WithMany()
                        .HasForeignKey("OnaylayanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Olusturan");

                    b.Navigation("Onaylayan");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.ZimmetStokDosya", b =>
                {
                    b.HasOne("BilgeLojistikIK.API.Models.ZimmetStok", "ZimmetStok")
                        .WithMany()
                        .HasForeignKey("ZimmetStokId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZimmetStok");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Departman", b =>
                {
                    b.Navigation("Pozisyonlar");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Egitim", b =>
                {
                    b.Navigation("PersonelEgitimleri");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.EkranYetkisi", b =>
                {
                    b.Navigation("KademeYetkileri");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Kademe", b =>
                {
                    b.Navigation("Pozisyonlar");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Personel", b =>
                {
                    b.Navigation("AltCalisanlar");

                    b.Navigation("IzinTalepleri");

                    b.Navigation("Kullanici");

                    b.Navigation("OnayladigiIzinler");

                    b.Navigation("PersonelEgitimleri");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.Pozisyon", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoEgitim", b =>
                {
                    b.Navigation("VideoAtamalar");

                    b.Navigation("VideoIzlemeler");

                    b.Navigation("VideoSorular");

                    b.Navigation("VideoYorumlar");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoKategori", b =>
                {
                    b.Navigation("VideoEgitimler");
                });

            modelBuilder.Entity("BilgeLojistikIK.API.Models.VideoSoru", b =>
                {
                    b.Navigation("VideoSoruCevaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
